version: '3'

services: 
    db:
        build: ./db
        ports: 
            - "9906:3306"
        env_file: 
            - ./konfiguracija.env

     
        
    
    web: 
        build: ./php
           
        depends_on: 
            - db
        volumes: 
            - ./php/src/:/var/www/html
        ports: 
            - "80:80"
        stdin_open: true
        tty: true
            